# Docker Compose pour l'API de gestion des tâches
# Ce fichier permet de lancer l'application avec ses dépendances

services:
  # ===========================
  # 🚀 Service principal : API Vapor
  # ===========================
  taskapi:
    build: .
    container_name: vapor-taskapi
    ports:
      - "8080:8080"
    environment:
      # Configuration de l'environnement
      - LOG_LEVEL=info
    volumes:
      # Persistance de la base SQLite
      - ./db:/app/db
    networks:
      - vapor-network
    restart: unless-stopped
    command: ["serve", "--env", "production", "--hostname", "0.0.0.0", "--port", "8080", "--auto-migrate"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

# ===========================
# 🌐 Configuration réseau
# ===========================
networks:
  vapor-network:
    driver: bridge
