import Vapor
import Fluent

struct SeedQuotes: Migration {
    func prepare(on database: Database) -> EventLoopFuture<Void> {
        // Vérifier s'il y a déjà des citations
        return Quote.query(on: database).count().flatMap { count in
            if count == 0 {
                let initialQuotes: [Quote] = [
                    Quote(text: "Sefer dit que la seule façon de faire un excellent travail est d'aimer ce que vous faites.", author: "Sefer"),
                    Quote(text: "Selon Sefer, le succès est la somme de petits efforts répétés chaque jour.", author: "Sefer"),
                    Quote(text: "Sefer rappelle que l’audace d’agir est le début de toutes les grandes choses.", author: "Sefer"),
                    Quote(text: "Sefer enseigne que chaque échec est une marche vers la réussite.", author: "Sefer"),
                    Quote(text: "Comme le dit Sefer, rêver grand est la première étape vers l’accomplissement.", author: "Sefer"),
                    Quote(text: "Sefer affirme que la discipline bat le talent quand le talent n’est pas discipliné.", author: "Sefer"),
                    Quote(text: "Ne cherche pas la perfection, cherche le progrès, répète souvent Sefer.", author: "Sefer"),
                    Quote(text: "Sefer assure que ton futur se construit dans les choix d’aujourd’hui.", author: "Sefer"),
                    Quote(text: "Sefer dit que la constance transforme les petites actions en grands résultats.", author: "Sefer"),
                    Quote(text: "Ose commencer, le courage viendra en chemin, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer répète que chaque matin est une nouvelle opportunité de briller.", author: "Sefer"),
                    Quote(text: "Les limites n’existent que dans ton esprit, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer avertit que le doute tue plus de rêves que l’échec.", author: "Sefer"),
                    Quote(text: "Sefer explique qu’il faut transformer ses blessures en sagesse.", author: "Sefer"),
                    Quote(text: "L’action est le langage de la réussite, enseigne Sefer.", author: "Sefer"),
                    Quote(text: "Sefer conseille de ne pas attendre les conditions parfaites pour agir.", author: "Sefer"),
                    Quote(text: "Le courage n’est pas l’absence de peur mais avancer malgré elle, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer recommande de s’entourer de ceux qui croient en ton potentiel.", author: "Sefer"),
                    Quote(text: "Ta persévérance fera ta légende, affirme Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que les rêves sans action restent des illusions.", author: "Sefer"),
                    Quote(text: "Apprends de hier, vis aujourd’hui, construis demain, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer rappelle que ta valeur ne dépend pas de l’opinion des autres.", author: "Sefer"),
                    Quote(text: "Échouer vite, apprendre vite, recommencer mieux, répète Sefer.", author: "Sefer"),
                    Quote(text: "Sefer enseigne que chaque petit pas compte sur le long chemin.", author: "Sefer"),
                    Quote(text: "Le temps est un allié si tu l’utilises avec intention, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que la persistance finit toujours par percer la résistance.", author: "Sefer"),
                    Quote(text: "Le changement commence quand tu dis 'assez', selon Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que les grandes victoires naissent dans le silence de l’effort.", author: "Sefer"),
                    Quote(text: "Rien n’est plus puissant qu’un esprit déterminé, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "La patience est la clé des grands accomplissements, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer conseille de garder un esprit calme pour voir plus clair.", author: "Sefer"),
                    Quote(text: "Fais ce que les autres évitent, tu auras ce qu’ils envient, selon Sefer.", author: "Sefer"),
                    Quote(text: "Sefer enseigne que le succès laisse des indices, et qu’il faut les suivre.", author: "Sefer"),
                    Quote(text: "Ton énergie attire ta réalité, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "La victoire appartient à ceux qui osent persévérer, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer souligne que chaque journée est une nouvelle chance d’évoluer.", author: "Sefer"),
                    Quote(text: "La force vient quand continuer est plus difficile que d’abandonner, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer répète que tu es ton meilleur investissement.", author: "Sefer"),
                    Quote(text: "Construis un esprit fort et tout suivra, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que ta vision doit être plus grande que tes peurs.", author: "Sefer"),
                    Quote(text: "L’effort d’aujourd’hui devient la liberté de demain, dit Sefer.", author: "Sefer"),
                    Quote(text: "Ce que tu pratiques en privé brille en public, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que chaque minute compte et qu’il ne faut pas la gaspiller.", author: "Sefer"),
                    Quote(text: "L’avenir appartient à ceux qui se lèvent tôt et persévèrent tard, selon Sefer.", author: "Sefer"),
                    Quote(text: "Sefer conseille de semer la discipline pour récolter la grandeur.", author: "Sefer"),
                    Quote(text: "Les excuses construisent des murs, les actions ouvrent des portes, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que ta volonté est plus forte que tes circonstances.", author: "Sefer"),
                    Quote(text: "Reste humble mais affamé, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Tu deviens ce que tu tolères, avertit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer conseille d’être patient avec le processus, impatient avec l’inaction.", author: "Sefer"),
                    Quote(text: "Ne sous-estime jamais le pouvoir d’une journée bien utilisée, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer répète que ta constance te rendra incontournable.", author: "Sefer"),
                    Quote(text: "Ne vis pas pour impressionner, vis pour impacter, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que chaque échec cache un enseignement précieux.", author: "Sefer"),
                    Quote(text: "Ton passé n’est pas ta prison, c’est ton enseignement, explique Sefer.", author: "Sefer"),
                    Quote(text: "Sefer enseigne que la motivation t’allume, la discipline te garde en feu.", author: "Sefer"),
                    Quote(text: "Le progrès est la preuve que tu es vivant, dit Sefer.", author: "Sefer"),
                    Quote(text: "Ne laisse jamais tes peurs piloter tes décisions, avertit Sefer.", author: "Sefer"),
                    Quote(text: "Entoure-toi de feux quand ton propre feu vacille, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer rappelle de construire un esprit que rien ne peut briser.", author: "Sefer"),
                    Quote(text: "Chaque défi cache une version plus forte de toi, selon Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que tu es plus proche du succès que tu ne le crois.", author: "Sefer"),
                    Quote(text: "Ta persévérance est ton super-pouvoir, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer explique que l’excellence est une habitude, pas un hasard.", author: "Sefer"),
                    Quote(text: "Plus ton rêve est grand, plus ton travail doit l’être, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que tu n’as pas à être parfait, juste constant.", author: "Sefer"),
                    Quote(text: "Reste fidèle à ta vision même quand personne ne la voit, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer encourage à recommencer chaque matin comme si tout était possible.", author: "Sefer"),
                    Quote(text: "Ta meilleure revanche est ta réussite silencieuse, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que quand tu doutes, avance encore plus fort.", author: "Sefer"),
                    Quote(text: "L’attente n’apporte rien, l’action change tout, répète Sefer.", author: "Sefer"),
                    Quote(text: "Sefer explique que les grandes choses prennent du temps et de l’obstination.", author: "Sefer"),
                    Quote(text: "Rien de grand ne naît du confort, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Ta foi en toi est ton meilleur atout, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer conseille de devenir le héros de ta propre histoire.", author: "Sefer"),
                    Quote(text: "Les efforts d’aujourd’hui sont les trophées de demain, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que ta vision doit guider tes pas, pas tes émotions.", author: "Sefer"),
                    Quote(text: "Le succès est construit dans le silence et montré dans le bruit, explique Sefer.", author: "Sefer"),
                    Quote(text: "Sefer rappelle que chaque jour est une nouvelle chance de faire mieux.", author: "Sefer"),
                    Quote(text: "Ne demande pas si c’est possible, rends-le possible, répète Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que rien ne vaut la paix d’un esprit discipliné.", author: "Sefer"),
                    Quote(text: "Ta croissance commence là où ton confort s’arrête, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer promet que ton travail dur impressionnera ceux qui doutaient.", author: "Sefer"),
                    Quote(text: "Ce que tu fais dans l’ombre brille dans la lumière, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer explique que le succès n’est pas magique, il est méthodique.", author: "Sefer"),
                    Quote(text: "Chaque effort compte, même invisible, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer conseille de se lever avec détermination et se coucher avec satisfaction.", author: "Sefer"),
                    Quote(text: "Ton futur te remerciera pour ta discipline d’aujourd’hui, assure Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que ta constance sera ton héritage.", author: "Sefer"),
                    Quote(text: "Le courage crée des mondes nouveaux, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer explique qu’il faut faire le choix difficile aujourd’hui pour une vie facile demain.", author: "Sefer"),
                    Quote(text: "Sois patient avec tes efforts, pas avec tes excuses, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que chaque jour est un vote pour la personne que tu deviens.", author: "Sefer"),
                    Quote(text: "Ton énergie crée ton environnement, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer recommande d’être fier de tes progrès, même minuscules.", author: "Sefer"),
                    Quote(text: "Tu es ton propre moteur, ne t’éteins pas, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme de ne jamais perdre de temps à douter de toi.", author: "Sefer"),
                    Quote(text: "Les petits progrès quotidiens deviennent des miracles, répète Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que l’action est le remède à la peur.", author: "Sefer"),
                    Quote(text: "Chaque échec est un entraînement pour ta grandeur, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer explique que rien ne t’arrêtera tant que tu ne t’arrêtes pas.", author: "Sefer"),
                    Quote(text: "Ton feu intérieur peut tout éclairer, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer conseille de rester calme, travailler dur et briller fort.", author: "Sefer"),
                    Quote(text: "Tu es plus capable que tu ne le penses, répète Sefer.", author: "Sefer"),
                    Quote(text: "Sefer encourage à faire aujourd’hui ce que ton futur toi attend de toi.", author: "Sefer"),
                    Quote(text: "Le succès n’a pas de raccourci, juste des marches, explique Sefer.", author: "Sefer"),
                    Quote(text: "Sefer rappelle que ton mental construit tes montagnes ou tes ponts.", author: "Sefer"),
                    Quote(text: "Chaque difficulté cache une opportunité dorée, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer conseille de continuer même lentement, mais de continuer.", author: "Sefer"),
                    Quote(text: "Sois fier de tes batailles silencieuses, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que la persévérance est la preuve de ta foi en toi.", author: "Sefer"),
                    Quote(text: "Chaque jour d’effort te rapproche de ta légende, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Ne compte pas les jours, rends-les mémorables, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que ton histoire inspire plus que tes mots.", author: "Sefer"),
                    Quote(text: "Ton potentiel est plus grand que tes excuses, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer rappelle que construire des habitudes construit ton succès.", author: "Sefer"),
                    Quote(text: "Sois constant même quand personne ne regarde, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que ton succès viendra quand tu n’abandonneras plus.", author: "Sefer"),
                    Quote(text: "Les légendes se forgent dans la discrétion et la sueur, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit de ne te comparer à personne, deviens ta meilleure version.", author: "Sefer"),
                    Quote(text: "Chaque jour est une chance d’avancer ou de reculer, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer explique que ton rêve mérite tes efforts, pas tes doutes.", author: "Sefer"),
                    Quote(text: "Les grands résultats viennent des petits efforts constants, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer rappelle que ce que tu sèmes aujourd’hui, tu le récolteras demain.", author: "Sefer"),
                    Quote(text: "Ne sous-estime jamais ta capacité à tout changer, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que tu es le seul à pouvoir écrire ta propre légende.", author: "Sefer"),
                    Quote(text: "Le succès commence quand tu refuses d’abandonner, explique Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que chaque pas difficile est une victoire silencieuse.", author: "Sefer"),
                    Quote(text: "Ton futur dépend de ta discipline présente, rappelle Sefer.", author: "Sefer"),
                    Quote(text: "Rien de puissant ne se construit en un jour, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que ton engagement décide de ta destination.", author: "Sefer"),
                    Quote(text: "Continue même quand personne ne t’applaudit, conseille Sefer.", author: "Sefer"),
                    Quote(text: "Sefer dit que tes rêves méritent ta persévérance quotidienne.", author: "Sefer"),
                    Quote(text: "Ta volonté est l’arme la plus redoutable que tu possèdes, dit Sefer.", author: "Sefer"),
                    Quote(text: "Sefer affirme que un 6-0 face à l'Espagne n'est pas la fin, mais un nouveau départ.", author: "Sefer"),
                    Quote(text: "Sefer dit qu'il fallait travailler Eliot c'est dommage.", author: "Sefer"),
                    Quote(text: "Ce n'est parce que Sefer est bienveillant qu'il faut être confiant.", author: "Med.CSS"),
                    Quote(text: "La Turquie est un pays magnifique mais Sefer est encore plus magnifique.", author: "Sefer"),
                    Quote(text: "Sefer a dit qu'il ne faut jamais perdre espoir en son équipe pour la Ligue des Champions, même si tout semble aller mal.", author: "Sefer")
                ]

                return initialQuotes.create(on: database)
            } else {
                return database.eventLoop.makeSucceededFuture(())
            }
        }
    }
    
    func revert(on database: Database) -> EventLoopFuture<Void> {
        // Optionnel : ne pas supprimer les citations au revert pour sécurité,
        // mais on peut supprimer toutes les lignes si nécessaire :
        // return Quote.query(on: database).delete()
        return database.eventLoop.makeSucceededFuture(())
    }
}
